### ISSUE TITLE
teamzusammenhalt fördern

### ISSUE THREAD

**Issue by marcuswilland** [quadrama/HtmlViewer#19]
arbeitsmotivation steigern durch igelbabies für alle
http://images.lifeline.de/img/leben-und-familie/origs90860/8286959444-w830-h830/Junger-Igel.jpg

**Comment by nilsreiter** [comment]
Approved. 

Baby-Elefanten sind auch ganz niedlich http://i.imgur.com/i74opGg.gifv

**Comment by marcuswilland** [comment]
völlig richtig, aber ich bin mir ziemlich sicher, dass - wenn man die miteinander spielen lässt -, am ende mindestens einer weint und einer tot ist
