### ISSUE TITLE
presence view akt-infos

### ISSUE THREAD

**Issue by marcuswilland** [quadrama/HtmlViewer#21]
in der übersicht sind die szenen-infos 1 - x, aber die akt-infos fehlen. 
gibt zig möglichkiten das darzustellen, aber mir fällt keine kluge ein. vllt reden wir da noch einmal drüber

**Comment by nilsreiter** [comment]
@marcuswilland das einzige was mir einfallen würde ist das umschaltbar zu machen, so dass man zwischen alt und Szene wechseln kann, ähnlich wie bei PresenceView2. 
Alles andere wird wahrscheinlich seeehr unübersichtlich.

**Comment by marcuswilland** [comment]
ist eine  Marginalie und kann erst einmal geparkt werden. 
aber da du knöpfe gut findest, wäre ich auch für die schalter-lösung :)

**Comment by marcuswilland** [comment]
völlig richtig, aber ich bin mir ziemlich sicher, dass - wenn man die miteinander spielen lässt -, am ende mindestens einer weint und einer tot ist
