### ISSUE TITLE
KLEIST Speaker tags einzelhinweise

### ISSUE THREAD

**Issue by marcuswilland** [quadrama/HtmlViewer#23]
r10b.0  prinz von homburg: Obrist Kottwitz und Kottwitz sind gleiche Figur
r0hz.0  Herrmannschlacht: "Ein Hauptmann" = 1x ein germanischer, 1x ein römischer Hauptmann
r10b.0  prinz von homburg: mehrere Personen in einem speaker-tag --> wie zuordnen?

**Comment by nilsreiter** [comment]
Das mit mehreren Personen ist ein Problem, das kann ich im Moment noch gar nicht richtig repräsentieren in den Daten. 

Im Prinzip würde man wollen, dass die Rede dann für alle Figuren mitgezählt wird, oder?

**Comment by nilsreiter** [comment]
Die Zuordnungen machen wir demnächst auch via github, aber da muss ich vorher noch was umbauen.

**Comment by nilsreiter** [comment]
Das muss zuerst passieren: quadrama/DramaNLP#9

**Comment by nilsreiter** [comment]
Multiple speakers: https://github.com/quadrama/DramaNLP/issues/10
